import { FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, LockKeyhole, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface AccessProps { setup?: boolean }

export default function Access({ setup = false }: AccessProps) {
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <div className="bg-secondary"><div className="container grid min-h-[calc(100vh-5rem)] items-center gap-16 py-16 lg:grid-cols-[1fr_0.8fr] lg:py-24"><div><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-brand-navy"><ArrowLeft className="h-4 w-4" /> Back to overview</Link><div className="mt-16 flex h-14 w-14 items-center justify-center rounded-md bg-brand-navy text-brand-gold"><LockKeyhole className="h-6 w-6" /></div><h1 className="mt-7 font-display text-5xl font-semibold text-brand-navy sm:text-6xl">{setup ? "Set up online access" : "Secure client access"}</h1><p className="mt-5 max-w-md text-lg leading-relaxed text-muted-foreground">{setup ? "Begin your secure access journey. Our team will guide you through the simple setup process." : "Access your ICBC Standard Bank services securely, wherever you are."}</p><div className="mt-10 flex items-center gap-3 text-sm text-muted-foreground"><ShieldCheck className="h-5 w-5 text-brand-gold" /> Protected by industry-standard security</div></div><div className="rounded-xl border border-border bg-background p-8 shadow-xl shadow-brand-navy/5 sm:p-10"><h2 className="font-display text-3xl font-semibold">{setup ? "Request access" : "Welcome back"}</h2><p className="mt-2 text-sm text-muted-foreground">{setup ? "Tell us a little about yourself." : "Sign in to continue to your secure portal."}</p>{submitted ? <div className="mt-8 rounded-md border border-brand-gold/40 bg-brand-gold/10 p-5 text-sm leading-relaxed text-brand-navy">Thank you. A member of our team will be in touch shortly.</div> : <form onSubmit={submit} className="mt-8 space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-medium">Work email</label><Input id="email" type="email" placeholder="you@company.com" required /></div>{setup && <div><label htmlFor="company" className="mb-2 block text-sm font-medium">Company name</label><Input id="company" placeholder="Your company" required /></div>}{!setup && <div><label htmlFor="password" className="mb-2 block text-sm font-medium">Password</label><Input id="password" type="password" placeholder="Enter your password" required /></div>}<Button type="submit" className="h-11 w-full bg-brand-navy hover:bg-brand-navy/90">{setup ? "Request access" : "Sign in"}<ArrowUpRight className="h-4 w-4" /></Button></form>}<p className="mt-7 border-t border-border pt-6 text-center text-xs text-muted-foreground">Need help? <Link to="/" className="font-medium text-brand-navy hover:text-brand-gold">Contact our team</Link></p></div></div></div>;
}
