import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleDollarSign, ClipboardCheck, FileSearch, Info, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const sectors = [
  { value: "real-estate", label: "Real estate development", detail: "Residential, commercial and mixed-use projects" },
  { value: "energy", label: "Oil & Gas and field development", detail: "Trading, infrastructure and production programs" },
  { value: "industrial", label: "Industrial development", detail: "Manufacturing, logistics and essential infrastructure" },
  { value: "government", label: "Government programs", detail: "Public-purpose projects and development mandates" },
];

const insights = [
  { label: "Real estate", title: "Build a financeable project story", text: "Bring planning status, sponsor contribution, valuation evidence and a clear repayment source together before requesting indicative terms." },
  { label: "Energy", title: "Structure around the trade cycle", text: "Oil & Gas facilities may be assessed around offtake, inventory, contracts, reserve data, insurance and operating controls." },
  { label: "Industrial", title: "Show execution readiness", text: "Industrial proposals are stronger when permits, supplier contracts, capex schedules and operating assumptions are easy to verify." },
  { label: "Government programs", title: "Separate impact from pricing", text: "Concessional or program-linked pricing remains subject to mandate eligibility, approvals, funding availability and documentation." },
];

const formatMoney = (value: number) => value.toLocaleString("en-US", { maximumFractionDigits: 0 });

export default function FinancingTools() {
  const [amount, setAmount] = useState("1000000");
  const [downPayment, setDownPayment] = useState("25");
  const [term, setTerm] = useState("36");
  const [rate, setRate] = useState("8");
  const [sector, setSector] = useState("real-estate");
  const [collateral, setCollateral] = useState("yes");
  const [documents, setDocuments] = useState("yes");
  const [result, setResult] = useState(false);

  const calculation = useMemo(() => {
    const principal = Math.max(0, Number(amount) * (1 - Number(downPayment) / 100));
    const monthlyRate = Number(rate) / 100 / 12;
    const months = Math.max(1, Number(term));
    const payment = monthlyRate ? principal * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1) : principal / months;
    return { principal, payment };
  }, [amount, downPayment, rate, term]);

  const precheckResult = collateral === "yes" && documents === "yes";
  const selectedSector = sectors.find((item) => item.value === sector) ?? sectors[0];

  return <div className="bg-secondary"><section className="bg-brand-navy text-white"><div className="container py-14 lg:py-20"><Link to="/financing/apply" className="inline-flex items-center gap-2 text-sm text-white/60 hover:text-brand-gold"><ArrowLeft className="h-4 w-4" /> Back to financing request</Link><div className="mt-12 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-brand-gold">Financing studio</p><h1 className="mt-4 font-display text-5xl font-semibold sm:text-6xl">Plan the opportunity before you apply.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-white/70">Use indicative tools to understand the shape of a secured-finance request across real estate, energy, industrial and public-purpose development.</p></div></div></section>
    <div className="container py-12 lg:py-16"><div className="grid gap-7 lg:grid-cols-[1.15fr_0.85fr]"><section className="rounded-xl border border-border bg-background p-7 shadow-sm sm:p-9"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-gold">01 · Indicative calculator</p><h2 className="mt-2 font-display text-3xl font-semibold text-brand-navy">Estimate facility payments</h2><p className="mt-2 text-sm text-muted-foreground">Illustrative only. Final pricing, structure and repayment terms require review.</p></div><CircleDollarSign className="h-7 w-7 text-brand-gold" /></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Project value or request<input value={amount} onChange={(event) => setAmount(event.target.value)} type="number" min="0" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" /></label><label className="text-sm font-medium">Down payment (%)<input value={downPayment} onChange={(event) => setDownPayment(event.target.value)} type="number" min="0" max="90" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" /></label><label className="text-sm font-medium">Term (months)<input value={term} onChange={(event) => setTerm(event.target.value)} type="number" min="1" max="360" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" /></label><label className="text-sm font-medium">Indicative annual rate (%)<input value={rate} onChange={(event) => setRate(event.target.value)} type="number" min="0" step="0.1" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" /></label></div><div className="mt-7 grid gap-4 rounded-lg bg-brand-navy p-5 text-white sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wider text-white/50">Illustrative facility</p><p className="mt-1 text-2xl font-semibold">USD {formatMoney(calculation.principal)}</p></div><div><p className="text-xs uppercase tracking-wider text-white/50">Estimated monthly payment</p><p className="mt-1 text-2xl font-semibold">USD {formatMoney(calculation.payment)}</p></div></div><p className="mt-4 flex gap-2 text-xs leading-relaxed text-muted-foreground"><Info className="mt-0.5 h-4 w-4 shrink-0 text-brand-gold" /> This estimate excludes fees, taxes, insurance, hedging costs and other transaction-specific expenses.</p></section>
      <section className="rounded-xl border border-border bg-background p-7 shadow-sm sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-gold">02 · Eligibility pre-check</p><h2 className="mt-2 font-display text-3xl font-semibold text-brand-navy">See what to prepare</h2><p className="mt-2 text-sm text-muted-foreground">A preparation guide, not a credit decision or promise of funding.</p><div className="mt-7 space-y-5"><label className="text-sm font-medium">Primary sector<select value={sector} onChange={(event) => setSector(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{sectors.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="text-sm font-medium">Do you have identifiable collateral?<select value={collateral} onChange={(event) => setCollateral(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="yes">Yes</option><option value="no">Not yet</option></select></label><label className="text-sm font-medium">Can you provide financial/project documents?<select value={documents} onChange={(event) => setDocuments(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="yes">Yes</option><option value="no">Not yet</option></select></label><Button type="button" onClick={() => setResult(true)} className="w-full bg-brand-navy hover:bg-brand-navy/90">Run preparation check <ClipboardCheck className="h-4 w-4" /></Button>{result && <div className={`rounded-lg border p-4 text-sm ${precheckResult ? "border-emerald-300 bg-emerald-50 text-emerald-900" : "border-brand-gold/40 bg-brand-gold/10 text-brand-navy"}`}><div className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4" /><div><p className="font-semibold">{precheckResult ? "Good starting position" : "More preparation recommended"}</p><p className="mt-1 text-xs leading-relaxed">{precheckResult ? `For ${selectedSector.label.toLowerCase()}, prepare ownership, valuation, repayment-source and identity materials for review.` : "You can still begin an exploratory conversation. Identifying collateral and core project evidence will improve the next step."}</p></div></div></div>}</div></section></div>
      <section className="mt-8 rounded-xl border border-border bg-background p-7 shadow-sm sm:p-9"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-gold">03 · Guided application preview</p><h2 className="mt-2 font-display text-3xl font-semibold text-brand-navy">Know the path before you begin</h2></div><Link to={`/financing/apply?market=${sector === "energy" ? "commodities" : "primary-markets"}`}><Button variant="outline" className="w-fit border-brand-navy text-brand-navy hover:bg-brand-navy hover:text-white">Start full request <ArrowRight className="h-4 w-4" /></Button></Link></div><div className="mt-7 grid gap-4 md:grid-cols-4">{[{ icon: ClipboardCheck, title: "Opportunity", text: "Project, sector, amount and purpose" }, { icon: ShieldCheck, title: "Security", text: "Collateral, valuation and contribution" }, { icon: FileSearch, title: "Evidence", text: "Metadata checklist and review materials" }, { icon: CheckCircle2, title: "Decision", text: "Appraisal, credit review and terms" }].map((item) => <div key={item.title} className="border border-border p-5"><item.icon className="h-5 w-5 text-brand-gold" /><p className="mt-4 text-sm font-semibold text-brand-navy">{item.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.text}</p></div>)}</div></section>
      <section className="mt-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-gold">04 · Sector insights</p><h2 className="mt-2 font-display text-3xl font-semibold text-brand-navy">Prepare for a stronger conversation</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2">{insights.map((insight) => <article key={insight.label} className="rounded-lg border border-border bg-background p-6"><p className="text-xs font-semibold uppercase tracking-wider text-brand-gold">{insight.label}</p><h3 className="mt-3 font-display text-2xl font-semibold text-brand-navy">{insight.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{insight.text}</p></article>)}</div></section><p className="mt-10 text-center text-xs leading-relaxed text-muted-foreground">All calculators, pre-checks and content are educational and indicative. Financing is subject to eligibility, due diligence, credit approval, documentation, available funding and applicable law. Concessional or government-program pricing is not guaranteed and may require separate program approval.</p></div></div>;
}
