import { Link } from "react-router-dom";
import { ArrowLeft, Bell, Check, Clock3, MailOpen } from "lucide-react";
import { Button } from "@/components/ui/button";

const messages = [
  { subject: "Opening deposit instructions", date: "20 Apr 2026", type: "Action required", text: "Your application has been approved in principle. Please review the opening deposit instructions to continue account activation.", action: "/opening-deposit?demo=1", actionLabel: "Review instructions", unread: true },
  { subject: "Application received", date: "20 Apr 2026", type: "Application update", text: "Your onboarding application and document checklist have been received. Our team will contact you if more information is required.", action: "/application-status?demo=1", actionLabel: "View application status", unread: false },
];

export default function Messages() {
  return <div className="bg-secondary"><div className="container py-10 lg:py-16"><Link to="/application-status?demo=1" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-brand-navy"><ArrowLeft className="h-4 w-4" /> Back to application status</Link><div className="mx-auto mt-12 max-w-4xl"><div className="flex flex-col justify-between gap-5 border-b border-border pb-7 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-brand-gold">Applicant portal</p><h1 className="mt-3 font-display text-4xl font-semibold text-brand-navy sm:text-5xl">Messages</h1><p className="mt-3 text-sm text-muted-foreground">Updates about your application and account onboarding.</p></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><Bell className="h-4 w-4 text-brand-gold" /> 1 unread message</div></div><div className="mt-8 space-y-4">{messages.map((message) => <article key={message.subject} className={`rounded-xl border bg-background p-6 shadow-sm sm:p-8 ${message.unread ? "border-brand-gold/60" : "border-border"}`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="flex items-start gap-3"><div className={`mt-0.5 flex h-9 w-9 items-center justify-center rounded-md ${message.unread ? "bg-brand-gold/15 text-brand-navy" : "bg-secondary text-muted-foreground"}`}>{message.unread ? <Bell className="h-4 w-4" /> : <MailOpen className="h-4 w-4" />}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl font-semibold">{message.subject}</h2>{message.unread && <span className="rounded-full bg-brand-gold/15 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-brand-navy">New</span>}</div><p className="mt-1 text-xs text-muted-foreground">{message.type} · {message.date}</p></div></div>{message.unread && <span className="inline-flex items-center gap-1 text-xs text-emerald-700"><Check className="h-3.5 w-3.5" /> Secure message</span>}</div><p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">{message.text}</p><Button asChild variant="outline" className="mt-6 border-brand-navy text-brand-navy hover:bg-brand-navy hover:text-white"><Link to={message.action}>{message.actionLabel} <Clock3 className="h-4 w-4" /></Link></Button></article>)}</div><div className="mt-8 rounded-xl border border-border bg-background p-6"><h2 className="font-display text-2xl font-semibold">Message preferences</h2><p className="mt-2 text-sm text-muted-foreground">Important application, compliance, and security messages are always sent. Notification preferences can be configured after account activation.</p></div></div></div></div>;
}
